### ISSUE TITLE
App Crashes after dismissing fingerprint Dialog [Android]

### ISSUE THREAD

**Issue by yarian** [naoufal/react-native-touch-id#106]
Repro steps:

1. Load screen which calls `TouchID.authenticate` automatically
2. Hit the back button
3. Go to home screen

App will crash with the following error:

```
03-30 17:07:59.958 13976 14135 E AndroidRuntime: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1858)
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1881)
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:688)
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at android.app.BackStackRecord.commit(BackStackRecord.java:646)
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at android.app.DialogFragment.show(DialogFragment.java:230)
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at com.rnfingerprint.FingerprintAuthModule.authenticate(FingerprintAuthModule.java:90)
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
03-30 17:07:59.958 13976 14135 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

Also noteworthy, once you hit the back button, we have a button on the screen that lets you prompt fingerprint again. This button stops working. Instead the callback immediately returns an error:
`ReactNativeJS: [Touch ID Error: Touch ID Error]`

I'm also seeing the following error often and it seems to be related to the first:

```
03-30 17:19:54.541 15261 15261 D AndroidRuntime: Shutting down VM
03-30 17:19:54.542 15261 15261 E AndroidRuntime: FATAL EXCEPTION: main
03-30 17:19:54.542 15261 15261 E AndroidRuntime: Process: com.coachconnect, PID: 15261
03-30 17:19:54.542 15261 15261 E AndroidRuntime: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
03-30 17:19:54.542 15261 15261 E AndroidRuntime: 	at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:30)
03-30 17:19:54.542 15261 15261 E AndroidRuntime: 	at com.rnfingerprint.DialogResultHandler.onError(DialogResultHandler.java:24)
03-30 17:19:54.542 15261 15261 E AndroidRuntime: 	at com.rnfingerprint.FingerprintDialog.onError(FingerprintDialog.java:125)
03-30 17:19:54.542 15261 15261 E AndroidRuntime: 	at com.rnfingerprint.FingerprintHandler.onAuthenticationError(FingerprintHandler.java:46)
03-30 17:19:54.542 15261 15261 E AndroidRuntime: 	at android.hardware.fingerprint.FingerprintManager$MyHandler.sendErrorResult(FingerprintManager.java:940)
03-30 17:19:54.542 15261 15261 E AndroidRuntime: 	at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:888)
03-30 17:19:54.542 15261 15261 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-30 17:19:54.542 15261 15261 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-30 17:19:54.542 15261 15261 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
03-30 17:19:54.542 15261 15261 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-30 17:19:54.542 15261 15261 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
03-30 17:19:54.542 15261 15261 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by Diego-Franco** [comment]
I think he can fix with this https://stackoverflow.com/a/10261449, I have the same crash

**Comment by francescosgherzi** [comment]
I fixed the error in this [PR](https://github.com/naoufal/react-native-touch-id/pull/118)

**Comment by yarian** [comment]
@francescosgherzi Posted a quick question about your solution on the PR but also wanted to call out that your PR only fixes the crashing portion. There is also the issue that once the back button is pressed, any efforts to start the dialog again don't work. This does not happen when pressing cancel.

**Comment by francescosgherzi** [comment]
Humm, you're right.
Fixing the crash was the "easy one".
I'll try figure that out and I'll update you in this thread.

**Comment by zibs** [comment]
This should be fixed on latest master now (on GH) and will be released to npm imminently (probably under 4.0.2).

**Comment by zibs** [comment]
4.0.2 is now on npm - give it a shot!

**Comment by Harshad24121999** [comment]
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1882)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1905)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:688)
       at android.app.BackStackRecord.commit(BackStackRecord.java:646)
       at android.app.DialogFragment.dismissInternal(DialogFragment.java:313)
       at android.app.DialogFragment.dismiss(DialogFragment.java:279)
       at com.rnfingerprint.FingerprintDialog.a(FingerprintDialog.java:8)
       at com.rnfingerprint.FingerprintHandler.onAuthenticationSucceeded(FingerprintHandler.java:2)
       at android.hardware.fingerprint.FingerprintManager.sendAuthenticatedSucceeded(FingerprintManager.java:1326)
       at android.hardware.fingerprint.FingerprintManager.access$800(FingerprintManager.java:91)
       at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:1235)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:349)
       at android.app.ActivityThread.main(ActivityThread.java:8241)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by Harshad24121999** [comment]
am on 4.4.1

**Comment by Harshad24121999** [comment]
I am on **4.4.1** 
  getting this... on crashylitics
  
  
  Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1882)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1905)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:688)
       at android.app.BackStackRecord.commit(BackStackRecord.java:646)
       at android.app.DialogFragment.dismissInternal(DialogFragment.java:313)
       at android.app.DialogFragment.dismiss(DialogFragment.java:279)
       at com.rnfingerprint.FingerprintDialog.a(FingerprintDialog.java:8)
       at com.rnfingerprint.FingerprintHandler.onAuthenticationSucceeded(FingerprintHandler.java:2)
       at android.hardware.fingerprint.FingerprintManager.sendAuthenticatedSucceeded(FingerprintManager.java:1326)
       at android.hardware.fingerprint.FingerprintManager.access$800(FingerprintManager.java:91)
       at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:1235)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:349)
       at android.app.ActivityThread.main(ActivityThread.java:8241)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
