### ISSUE TITLE
Intermittent crashes on Android

### ISSUE THREAD

**Issue by rikur** [naoufal/react-native-touch-id#124]
I get crashes very often on a physical device -- never on emulator. Here are example stacktraces:

```
05-31 09:10:48.422  4649  4649 I System.out: 	at java.lang.Thread.getStackTrace(Thread.java:1566)
05-31 09:10:48.422  4649  4649 I System.out: 	at com.rnfingerprint.DialogResultHandler.onError(DialogResultHandler.java:22)
05-31 09:10:48.422  4649  4649 I System.out: 	at com.rnfingerprint.FingerprintDialog.onError(FingerprintDialog.java:132)
05-31 09:10:48.422  4649  4649 I System.out: 	at com.rnfingerprint.FingerprintHandler.onAuthenticationError(FingerprintHandler.java:37)
05-31 09:10:48.422  4649  4649 I System.out: 	at android.hardware.fingerprint.FingerprintManager$MyHandler.sendErrorResult(FingerprintManager.java:845)
05-31 09:10:48.422  4649  4649 I System.out: 	at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:816)
05-31 09:10:48.422  4649  4649 I System.out: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-31 09:10:48.422  4649  4649 I System.out: 	at android.os.Looper.loop(Looper.java:159)
05-31 09:10:48.422  4649  4649 I System.out: 	at android.app.ActivityThread.main(ActivityThread.java:6139)
05-31 09:10:48.422  4649  4649 I System.out: 	at java.lang.reflect.Method.invoke(Method.java:-2)
05-31 09:10:48.422  4649  4649 I System.out: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
05-31 09:10:48.423  4649  4649 I System.out: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

```
05-31 09:10:48.406  4649  4649 I System.out: 	at java.lang.Thread.getStackTrace(Thread.java:1566)
05-31 09:10:48.406  4649  4649 I System.out: 	at com.rnfingerprint.DialogResultHandler.onError(DialogResultHandler.java:22)
05-31 09:10:48.406  4649  4649 I System.out: 	at com.rnfingerprint.FingerprintDialog.onError(FingerprintDialog.java:132)
05-31 09:10:48.406  4649  4649 I System.out: 	at com.rnfingerprint.FingerprintHandler.onAuthenticationError(FingerprintHandler.java:37)
05-31 09:10:48.406  4649  4649 I System.out: 	at android.hardware.fingerprint.FingerprintManager$MyHandler.sendErrorResult(FingerprintManager.java:845)
05-31 09:10:48.406  4649  4649 I System.out: 	at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:816)
05-31 09:10:48.406  4649  4649 I System.out: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-31 09:10:48.406  4649  4649 I System.out: 	at android.os.Looper.loop(Looper.java:159)
05-31 09:10:48.406  4649  4649 I System.out: 	at android.app.ActivityThread.main(ActivityThread.java:6139)
05-31 09:10:48.406  4649  4649 I System.out: 	at java.lang.reflect.Method.invoke(Method.java:-2)
05-31 09:10:48.406  4649  4649 I System.out: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
05-31 09:10:48.406  4649  4649 I System.out: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

I tried to add a safety check before invoking the callback, but to no avail:
```
    @Override
    public void onError(String errorString) {
      if(FingerprintAuthModule.inProgress){
        FingerprintAuthModule.inProgress = false;
        errorCallback.invoke(errorString);
      }
    }
```

My best guess is that there are two instances of FingerprintAuthModule and two different threads invoke the callback. Look at the timestamps, the callback invocations happen about 20ms apart.

I tested this on `master`.

**Comment by zibs** [comment]
Can you try running on 4.0.3 and comment here or open a new issue if you're still getting crashes? Thanks!
