### ISSUE TITLE
java.lang.NullPointerExceptionAttempt

### ISSUE THREAD

**Issue by rajsuvariya** [naoufal/react-native-touch-id#137]
```

Fatal Exception: java.lang.NullPointerExceptionAttempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference Raw Text
--
  | com.rnfingerprint.FingerprintAuthModule.isSupported (FingerprintAuthModule.java:55)
  | java.lang.reflect.Method.invoke (Method.java)
  | com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:374)
  | com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:162)
  | com.facebook.react.bridge.queue.NativeRunnable.run (NativeRunnable.java)
  | android.os.Handler.handleCallback (Handler.java:869)
  | android.os.Handler.dispatchMessage (Handler.java:101)
  | com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:31)
  | android.os.Looper.loop (Looper.java:206)
  | com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run (MessageQueueThreadImpl.java:194)
  | java.lang.Thread.run (Thread.java:764)


```

We are getting this crash.

**Comment by zibs** [comment]
Can you post any more of your code or you set up? I'm not sure if I'm able to reproduce this at all...

**Comment by dahudson88** [comment]
I am getting this issue as well:

LogCat Output:
```
12-05 10:34:20.454 11408 11430 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
12-05 10:34:20.454 11408 11430 E AndroidRuntime: 	at com.rnfingerprint.FingerprintAuthModule.isSupported(FingerprintAuthModule.java:55)
12-05 10:34:20.454 11408 11430 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-05 10:34:20.454 11408 11430 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
12-05 10:34:20.454 11408 11430 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
12-05 10:34:20.454 11408 11430 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
12-05 10:34:20.454 11408 11430 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
12-05 10:34:20.454 11408 11430 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-05 10:34:20.454 11408 11430 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
12-05 10:34:20.454 11408 11430 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
12-05 10:34:20.454 11408 11430 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
12-05 10:34:20.454 11408 11430 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)

```
This is where the error is called in the react-native-touch-id module FingerprintAuthModule.java
```
@ReactMethod
  public void isSupported(Callback reactErrorCallback, Callback reactSuccessCallback) {
    keyguardManager =
            (KeyguardManager) getCurrentActivity().getSystemService(Context.KEYGUARD_SERVICE);
    fingerprintManager =
            (FingerprintManager) getCurrentActivity().getSystemService(Context.FINGERPRINT_SERVICE);
    if(!isFingerprintAuthAvailable()) {
      reactErrorCallback.invoke("Not supported.");
    } else {
      reactSuccessCallback.invoke("Is supported.");
    }
    return ;
  }
```

My use...

```
 if (Platform.OS === 'android' && Platform.Version <= 23) {

        }
        else {
            TouchID.isSupported()
                .then(biometryType => {
                    // Success code
                    if (biometryType === 'FaceID') {
                        this.setState({ hasBiometric: true, idType: 'FaceID' })
                    } else {
                        this.setState({ hasBiometric: true, idType: 'TouchID' })
                    }
                })
                .catch(error => {
                    // Failure code
                });
```
