### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by hweister** [naoufal/react-native-touch-id#198]
Here attached the log, it looks like the same problem --- in FingerprintDialog.java file, line 169 and line 184, we must make sure this.dialogCallback had set before call its onCancelld and onAuthenticated function.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.rnfingerprint.FingerprintDialog$DialogResultListener.onAuthenticated()' on a null object reference
       at com.rnfingerprint.FingerprintDialog.onAuthenticated(FingerprintDialog.java:169)
       at com.rnfingerprint.FingerprintHandler.onAuthenticationSucceeded(FingerprintHandler.java:48)
       at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedSucceeded(FingerprintManager.java:958)
       at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:878)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7425)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.rnfingerprint.FingerprintDialog$DialogResultListener.onCancelled()' on a null object reference
       at com.rnfingerprint.FingerprintDialog.onCancelled(FingerprintDialog.java:184)
       at com.rnfingerprint.FingerprintDialog$2.onKey(FingerprintDialog.java:86)
       at android.app.Dialog.dispatchKeyEvent(Dialog.java:808)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:352)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5191)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5059)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4578)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4631)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4597)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4737)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4605)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4794)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4578)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4631)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4597)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4605)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4578)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4631)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4597)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4770)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4933)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2580)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2090)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2081)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2557)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:165)
       at android.app.ActivityThread.main(ActivityThread.java:6806)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by tlow92** [comment]
Any update on this? 
Facing the same problem. Got ~40 events on this ranging from Android 7 to Android 9.

**Comment by kevinetore** [comment]
Same issue here, Android versions range from 8 to 9. `"react-native-touch-id": "^4.4.1"`.

**Comment by gre** [comment]
Did someone figured out a way/pattern to reproduce the bug?

**Comment by elirangoshen** [comment]
+1 have some logs as well

**Comment by sunpandeydeloitte** [comment]
+1 any solution

**Comment by asimsikka** [comment]
+1 any solution?

**Comment by khunghang16** [comment]
+1 any solution

**Comment by tlow92** [comment]
> +1 any solution

I suggest, you move to expo-local-authentication https://docs.expo.dev/versions/v46.0.0/sdk/local-authentication/

This repo here is dead.
