### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by aujisti-ador** [naoufal/react-native-touch-id#240]
after adding npm i `--save react-native-touch-id` when i added `react-native link react-native-touch-id` then i got the error. 
```
Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at merge_obj (/Users/redwan-ulansari/Desktop/react-rnd/node_modules/xcode/lib/parser/pbxproj.js:1883:25)
    at merge_obj (/Users/redwan-ulansari/Desktop/react-rnd/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/Users/redwan-ulansari/Desktop/react-rnd/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/Users/redwan-ulansari/Desktop/react-rnd/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/Users/redwan-ulansari/Desktop/react-rnd/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/Users/redwan-ulansari/Desktop/react-rnd/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/Users/redwan-ulansari/Desktop/react-rnd/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/Users/redwan-ulansari/Desktop/react-rnd/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/Users/redwan-ulansari/Desktop/react-rnd/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
    at merge_obj (/Users/redwan-ulansari/Desktop/react-rnd/node_modules/xcode/lib/parser/pbxproj.js:1888:24)
```
how to fix it? Thanks.

**Comment by 1415225876** [comment]
I have the same problem,how to fix it?
