### ISSUE TITLE
Android version < 5.0 crashes while building

### ISSUE THREAD

**Issue by 2vm** [naoufal/react-native-touch-id#68]
Got an error `java.lang.VerifyError: com/rnfingerprint/FingerprintAuthModule` while tried to run `react-native run-android` which actually makes impossible to launch the application on android version 4.4.2 and 4.4.4. On android 5+ it works fine.
The trouble shooting while application compiling, because even if I remove all JS code with importing/using TouchID in project the error is still.

![error](https://user-images.githubusercontent.com/29550205/35272844-4400c5fe-003f-11e8-9576-b82fbfcb8a27.png)
![export](https://user-images.githubusercontent.com/29550205/35272845-441d8ca2-003f-11e8-8f84-66b2e91cc03d.png)

Full error code: 
`
01-23 12:23:29.021 28712-30617/io.apla E/dalvikvm: Could not find class 'android.hardware.fingerprint.FingerprintManager', referenced from method com.rnfingerprint.FingerprintAuthModule.authenticate

01-23 11:05:39.361 12299-12614/io.apla E/AndroidRuntime: FATAL EXCEPTION: Thread-131
                                                         java.lang.VerifyError: com/rnfingerprint/FingerprintAuthModule
                                                             at com.rnfingerprint.FingerprintAuthPackage.createNativeModules(FingerprintAuthPackage.java:18)
                                                             at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
                                                             at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1196)
                                                             at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1166)
                                                             at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1099)
                                                             at com.facebook.react.ReactInstanceManager.access$800(ReactInstanceManager.java:112)
                                                             at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:927)
                                                             at java.lang.Thread.run(Thread.java:856)`

Is there any solutions? Or at least opportunity to dynamically linking the library depends on Android version?

**Comment by 2vm** [comment]
fixed here https://github.com/naoufal/react-native-touch-id/pull/70

**Comment by zibs** [comment]
Will merge #70.
