### ISSUE TITLE
[Android] Random crash using with react-native-navigation

### ISSUE THREAD

**Issue by replecta** [naoufal/react-native-touch-id#94]
Help, I'm using Wix's navigation and i sometimes get error when launching the app regardless of calling the authenticate.
<pre>
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
                                                                         at com.rnfingerprint.FingerprintAuthModule.isSupported(FingerprintAuthModule.java:55)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
                                                                         at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                                         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                         at android.os.Handler.handleCallback(Handler.java:790)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                         at android.os.Looper.loop(Looper.java:164)
                                                                         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                                         at java.lang.Thread.run(Thread.java:764)
</pre>

**Comment by TheDirtyCalvinist** [comment]
This is because it is attempting to get the system service from the current activity (which hasn't been created yet) instead of the react application context.  When accessing the system services, you can use`getReactApplicationContext` instead of `getCurrentActivity`, but that will require forking the repo and using a custom version.

**Comment by johakr** [comment]
@TheDirtyCalvinist Is there some downside of always using `getReactApplicationContext` over `getCurrentActivity`?
